# path to the data folder
# example --> data_dir: 'data_dir/single_file/'
data_dir: ['../data/',]

# path to the statistics categories
# example --> stats_category_path: 'stats_categories.txt'
stats_category_path: 'stats_categories.txt'

# valid surface (ie: surface you want to extract data from)
# ZERO INDEXED ie: Number of Surface - 1
valid_surface: 6