# path to the data folder
# example --> data_dir: 'data_dir/single_file/'
data_dir: ['/home/shehan/Documents/nih_projects/parsers/data/temp']

# valid surface (ie: surface you want to extract data from)
# NOT ZERO INDEX, VALUES START AT 1
valid_surface: 4

# type of data extraction: surface, track or first
#parser_type: 'surface'

# path to the statistics categories
# example --> stats_category_path: 'stats_categories.txt'
# ensure the right category txt file is provided based on parser type
stats_category_path: 'stats_categories_first.txt'
