# path to the data folder
# example --> data_dir: 'data_dir/single_file/'
# multiple directories possible just seperate each with a comma.
data_dir: ['\\niaid-fas1\Bioimaging\Users\rogandc\06162023 SIV infected VLP 6-color\' , '\\niaid-fas1\Bioimaging\Users\rogandc\06082023 SIV infected VLP 6-color\' , '\\niaid-fas1\Bioimaging\Users\rogandc\04102023 VLP ALN ILN 6c\' , '\\niaid-fas1\Bioimaging\Users\rogandc\04052023 SHIV aLN iLN 6-color\']

# each data directory MUST have a matching save directory
save_dir: ['\\niaid-fas1\Bioimaging\Users\rogandc\06162023 SIV infected VLP 6-color\track' , '\\niaid-fas1\Bioimaging\Users\rogandc\06082023 SIV infected VLP 6-color\track' , '\\niaid-fas1\Bioimaging\Users\rogandc\04102023 VLP ALN ILN 6c\track' ,'\\niaid-fas1\Bioimaging\Users\rogandc\04052023 SHIV aLN iLN 6-color\track']

# valid surface (ie: surface you want to extract data from)
# NOT ZERO INDEX, VALUES START AT 1
valid_surface: [1, 2, 3, 4, 5]

# type of data extraction: surface, track or first
parser_type: 'track'

# path to the statistics categories
# example --> stats_category_path: 'stats_categories.txt'
# ensure the right category txt file is provided based on parser type
stats_category_path: 'txt_files/stats_categories_track.txt'
