# List of directories that contains .ims files
data_dir: ['/home/shehan/Documents/nih_projects/parsers/data/surface_track_parser_dev_data']

# File Path: Optional If You want to Run a single .ims File
save_dir: ["results/new"]

# Surface of Interest NOT ZERO INDEX ie: START WITH 1
# If ALL surfaces are needed use valid_surfaces = -1
#valid_surfaces: [1,2,3,7,12]
valid_surfaces: -1 

cpu_cores: 28