# List of directories that contains .ims files
data_dir: ["C:/Users/perer/Downloads/FIX/FIX/04052023 SHIV aLN iLN 6-color/04052023 SHIV aLN iLN 6-color",
      "C:/Users/perer/Downloads/FIX/FIX/F1", "C:/Users/perer/Downloads/FIX/FIX/F2"]

# File Path: Optional If You want to Run a single .ims File
save_dir: ["results/new", "results/f1", "results/f2"]

# Surface of Interest NOT ZERO INDEX ie: START WITH 1
# If ALL surfaces are needed use valid_surfaces = -1
valid_surfaces: [1,2,3,7,12]
#valid_surfaces: -1 

cpu_cores: 28