
# String 
parser_type: Surface

# List of directories that contains .ims files
dir_paths: 

# File Path: Optional If You want to Run a single .ims File
file_path: 

# Run Type: dir or file
# specifies to run using dir_paths or file_path
run_type: dir

# Surface of Interest
surface

